# Generated by Django 5.1.2 on 2024-10-14 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comyany',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jobseek.company'),
            preserve_default=False,
        ),
    ]
