# Generated by Django 5.1.2 on 2024-10-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseek', '0002_alter_customuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(through='jobseek.JobSkill', to='jobseek.skill'),
        ),
    ]
