# Generated by Django 5.1.2 on 2024-10-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseek', '0002_application_comyany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='comyany',
            new_name='Company',
        ),
    ]
