# Generated by Django 5.1.2 on 2024-10-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseek', '0003_rename_comyany_application_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Company',
            new_name='company',
        ),
    ]
