# Generated by Django 5.1.2 on 2024-10-09 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseek', '0003_job_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobskill',
            old_name='skill',
            new_name='skills',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
    ]
