# Generated by Django 5.1.2 on 2024-10-11 01:40

import wallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletaddress',
            name='address',
            field=models.CharField(default=wallet.models.generate_wallet_address, max_length=10, unique=True),
        ),
    ]
