# Generated by Django 5.1.2 on 2024-10-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_walletaddress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletaddress',
            name='address',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
